### ISSUE TITLE
Error using glmDegree for multinomial models

### ISSUE THREAD

**Issue by ggautreau** [sysbiomed/glmSparseNet#1]
Hello,

I'm currently working on the regression of different phenotypes giving a matrix of binary observation together with a graph linking the feature.

Your work fits my needs but I have an error.

I use your package using the following R code:
```
library(rgexf)
library("glmSparseNet")

x <- model.matrix(pheno~.,data_t_col_known_pheno)
y <- as.numeric(data_t_col_known_pheno$pheno)
g = read.gexf("graph.gexf")
ig = gexf.to.igraph(g)
sub_ig<- induced_subgraph(ig,rownames(data))
adj_sub_ig = as_adjacency_matrix(sub_ig, attr="weight",sparse=FALSE)
save(x,y,adj_sub_ig,file="objects.RData")
cv.out <- cv.glmDegree(x,y,network=adj_sub_ig,network.options.default(unweighted=FALSE, min.degree = 1),alpha=.1,family = "multinomial")
res <-coef(cv.out)
```

And I get the following Error:
```
Error in approx(lambda, seq(lambda), sfrac) : 
  need at least two non-NA values to interpolate
```

Here is the Rdata file (in a zip archive) containing the variables x, y, and adj_sub_ig.

[objects.zip](https://github.com/sysbiomed/glmSparseNet/files/2345797/objects.zip)

Can you help me?

Bye.

**Comment by averissimo** [comment]
The problem seems to be that when estimating 'good' `lambda` values it settles with `cv.out$lambda = c(NA, Inf, Inf, Inf, Inf, Inf)`

This never happened to me, but there is a way around this: 

* running `glmnet` without network to estimate the lambda values

```
model.out.orig <- glmnet(x, y, alpha=.1, family = "multinomial")

cv.out <- cv.glmDegree(x, y, network = adj_sub_ig, network.options.default(unweighted=FALSE, min.degree = .1), alpha=.1, family = "multinomial", lambda = model.out.orig$lambda))
```

Playing with this lambda value will help determine how sparse is the model, i.e. `lambda = c(model.out.orig$lambda, model.out.orig$lambda * 10, model.out.orig$lambda * 100)`

**Comment by ggautreau** [comment]
Ok thank you for your advice, it seems to work with this trick.

Bye

**Comment by averissimo** [comment]
Cool, closing the issue.. Hope the package helps in your work.

Note that in high dimensional spaces I've been having more success using `glmHub` instead of `glmDegree`
