### ISSUE TITLE
Externals API error

### ISSUE THREAD

**Issue by KingJuliusss** [sysbiomed/glmSparseNet#4]
Error connecting to Hallmarks API.

**Comment by averissimo** [comment]
This will be corrected in BiocConductor 3.14 release, I'll backport the corrections to 3.13 in a few days.

Thanks for reporting, keeping this open until it's fixed in 3.13

**Comment by averissimo** [comment]
It's not possible to update 3.13 anymore _(current version)_ as BioConductor is in the process of releasing the new version.

If you want to use the extension right now, you can use Bioc devel or install directly from github with the following command:

```
remotes::install_github('sysbiomed/glmSparseNet')
```
