### ISSUE TITLE
Package failing on Bioconductor

### ISSUE THREAD

**Issue by Kayla-Morrell** [sysbiomed/glmSparseNet#6]
Hello André,
 
The next Bioconductor release 3.15 is scheduled for April 27th. Commits to the
current 3.14 release should be made by April 8th and the last day to commit to
the devel branch is April 22nd. We like to make an effort to have all
Bioconductor packages building and checking without ERROR or TIMEOUT in both
release and devel versions. Our team has attempted to reach you on multiple occasions
with no success. **If changes are not made to fix this package it will be deprecated.**
 
Currently your package is producing an ERROR across all builders in the release and 
devel version of Bioconductor. Could you please investigate the error as soon
as possible?
 
Release version - https://bioconductor.org/checkResults/3.14/bioc-LATEST/glmSparseNet/
Devel version - https://bioconductor.org/checkResults/3.15/bioc-LATEST/glmSparseNet/
 
If you need any assistance please feel free to ask questions at
[bioc-devel@r-project.org](mailto:bioc-devel@r-project.org).
 
Thank you,
Kayla

**Comment by averissimo** [comment]
Thanks, I corrected it before the release and it's still building without errors as of now in current and devel
